name: meu_caderninho
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.4
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^4.3.0
  image_picker: ^1.0.7
  cloud_firestore: ^4.13.2
  flutter_multi_formatter: ^2.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_native_splash: ^2.3.5

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png
  android: true
  ios: true
  web: true
